/* A continuous three-arena course: each third takes roughly 30 seconds at base pace.
   The race SIMULATION (progress, finish detection) is driven from TWO independent
   timing sources — setInterval AND requestAnimationFrame — both calling the same
   advance() function. Browsers throttle background/inactive timers differently (and
   a real device confirmed setInterval alone can stall out with progress stuck just
   short of the finish), so relying on a single mechanism was still a single point of
   failure. Whichever of the two is still actually firing is enough on its own to
   keep the race moving and finish it correctly; advance() is safe to call from both
   because it always computes dt from real elapsed time since its own last run. */
const Race={canvas:null,c:null,racers:[],start:0,lastSim:0,elapsed:0,leg:'swim',locked:false,done:false,nextCPU:0,camera:0,raceId:0,simId:null,
init(){this.canvas=document.querySelector('#raceCanvas');this.c=this.canvas.getContext('2d')},
/* raceId guards against a double-click on Start Race (or any other double-invocation) leaving two loops fighting over shared state — every scheduled tick/frame carries the id of the race that queued it and bails out immediately if a newer race has since started. */
startRace(){let id=++this.raceId;this.racers=Racers.reset();this.history=[];this.currentQuestion=null;this.start=this.lastSim=performance.now();this.elapsed=0;this.done=false;this.camera=0;this.leg='swim';this.nextCPU=1.8;document.querySelector('#progressFill').style.width='0%';document.querySelector('#progressLabel').textContent='0%';this.question();this.startSim(id);this.startRender(id)},
startSim(id){if(this.simId)clearInterval(this.simId);this.simId=setInterval(()=>this.advance(performance.now(),id),50)},
startRender(id){let frame=t=>{if(id!==this.raceId||this.done)return;this.advance(performance.now(),id);if(this.done)return;try{this.draw(t/1000);this.ui()}catch(e){console.error('Race render error (non-fatal — the race itself is unaffected):',e)}requestAnimationFrame(frame)};requestAnimationFrame(frame)},
getLeg(){let p=this.racers[0].progress;return p<1/3?'swim':p<2/3?'bike':'run'},
question(){let q=Questions.make(this.leg),box=document.querySelector('#answers');this.currentQuestion=q;this.questionStart=performance.now();document.querySelector('#question').textContent=q.text;box.innerHTML='';q.options.forEach((n,i)=>{let b=document.createElement('button');b.className='answer';b.innerHTML=`<b>${i+1}</b>${n}`;b.onclick=()=>this.answer(n===q.answer,n,b);box.append(b)})},
/* Impulse is a FIXED fraction of total race progress (~0.56%, matching what "0.5s on a 90s race" originally worked out to), not fixed seconds — dividing fixed seconds by the (now much shorter) target made each wrong answer proportionally far more punishing than intended, to the point a losing streak could stall the player's forward progress for a long stretch right when they're close to finishing. This keeps the risk/reward feel consistent regardless of race length, and guarantees the player is always progressing forward on net even in a worst-case all-wrong run. */
applyImpulse(r,correct){let frac=.5/90;r.boost=(correct?1:-1)*frac/.6;r.boostLeft=.6;r.flash=correct?'SURGE!':'STUMBLE!';r.flashLeft=.6},
answer(right,choice,button){if(this.locked||this.done)return;this.locked=true;/* Everything risky (DOM, audio) is isolated so a failure here can never leave the game stuck on this question forever. */try{this.history.push({text:this.currentQuestion.text,choice,answer:this.currentQuestion.answer,correct:right,time:(performance.now()-this.questionStart)/1000});document.querySelectorAll('.answer').forEach(b=>b.disabled=true);button.classList.add(right?'correct':'wrong');this.applyImpulse(this.racers[0],right);Audio[right?'correct':'wrong']();document.querySelector('#feedback').textContent=right?'Correct! Smooth speed burst!':'Keep going — next question!'}catch(e){console.error('Race.answer error:',e)}setTimeout(()=>{this.locked=false;document.querySelector('#feedback').textContent='';this.question()},620)},
/* This is the ONLY place that decides the race is finished. It's called from both setInterval and requestAnimationFrame (see the comment at the top of this file), so it must be safe to invoke from either — dt is always computed from real elapsed time since its own last run, so calling it twice in quick succession from both sources just means smaller, more frequent steps, not double-counted progress. */
advance(now,id){if(id!==this.raceId||this.done)return;try{let dt=Math.max(0,(now-this.lastSim)/1000);this.lastSim=now;this.elapsed=(now-this.start)/1000;this.racers.forEach(r=>{if(r.finished)return;let extra=r.boostLeft>0?r.boost:0;r.progress=Math.max(0,r.progress+dt/r.target+extra*dt);r.boostLeft=Math.max(0,(r.boostLeft||0)-dt);r.flashLeft=Math.max(0,(r.flashLeft||0)-dt)});if(this.elapsed>this.nextCPU){this.nextCPU+=1.8+Math.random()*1.5;this.racers.slice(1).forEach(r=>this.applyImpulse(r,Math.random()<(r.target<=75?.75:.63)))}let leg=this.getLeg();if(leg!==this.leg){this.leg=leg;this.showTransition(leg);this.question()}this.racers.forEach(r=>{if(r.progress>=1&&!r.finished){r.finished=true;r.finish=this.elapsed}});if(this.racers[0].finished){this.done=true;if(this.simId){clearInterval(this.simId);this.simId=null}this.finishRace()}}catch(e){console.error('Race.advance error:',e);if(this.racers&&this.racers[0]&&this.racers[0].progress>=1&&!this.done){this.done=true;let r=this.racers[0];if(!r.finished){r.finished=true;r.finish=this.elapsed}if(this.simId){clearInterval(this.simId);this.simId=null}try{this.finishRace()}catch(e2){console.error('finishRace recovery failed:',e2)}}}},
finishRace(){Results.show(this.racers,this.racers[0].finish,this.history)},
showTransition(leg){let el=document.querySelector('#transition'),info={bike:['BIKE LEG','MULTIPLICATION'],run:['FINAL RUN','MIXED MATH']}[leg];el.innerHTML=`<span>${info[0]}<small>${info[1]}</small></span>`;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),750)},
ui(){let n={swim:['LEG 1 OF 3','SWIM • ADDITION'],bike:['LEG 2 OF 3','BIKE • MULTIPLICATION'],run:['LEG 3 OF 3','RUN • MIXED MATH']}[this.leg];document.querySelector('#legLabel').textContent=n[0];document.querySelector('#legName').textContent=n[1];document.querySelector('#timer').textContent=Main.time(this.elapsed);/* Never show 100% until the race is actually done — rounding up (Math.round) let the bar hit "100%" while progress/done were still false, so the screen looked finished and frozen for a stretch before the finish actually fired. Floor it, and cap the display at 100 only once `done` is true. */let pct=this.done?100:Math.min(99,Math.floor(this.racers[0].progress*100));document.querySelector('#progressFill').style.width=pct+'%';document.querySelector('#progressLabel').textContent=pct+'%';document.querySelector('#scoreboard').innerHTML=this.racers.map(r=>`<div class="score-row" style="top:${120+r.lane*24}px"><i class="score-dot" style="background:${r.color}"></i>${r.name}</div>`).join('');let p=this.racers[0];document.querySelector('#debugInfo').textContent=`debug: progress=${(p.progress*100).toFixed(2)}% finished=${p.finished} done=${this.done} elapsed=${this.elapsed.toFixed(1)}s leg=${this.leg} raceId=${this.raceId} locked=${this.locked}`},
line(c,x,label){c.save();c.translate(x,0);c.fillStyle='#fff';c.fillRect(-6,92,12,360);c.fillStyle='#18334e';c.font='900 13px Arial';c.textAlign='center';c.fillText(label,0,82);c.restore()},
arena(c,start,type,t){let w=1000;c.save();c.translate(start,0);if(type==='swim'){c.fillStyle='#a4e8f6';c.fillRect(0,0,w,500);c.fillStyle='#69c8df';c.fillRect(0,110,w,390);c.strokeStyle='#dcfbff';c.lineWidth=3;for(let y=145;y<500;y+=52){c.beginPath();for(let x=0;x<w;x+=24)c.lineTo(x,y+Math.sin(x/28+t*3)*4);c.stroke()}}else if(type==='bike'){c.fillStyle='#aee7ff';c.fillRect(0,0,w,500);c.fillStyle='#86c86d';c.fillRect(0,95,w,405);c.fillStyle='#5c6570';c.fillRect(0,146,w,354)}else{c.fillStyle='#b9e8ff';c.fillRect(0,0,w,500);c.fillStyle='#86c966';c.fillRect(0,95,w,405);c.fillStyle='#d75b52';c.fillRect(0,146,w,354)}if(type!=='swim'){c.strokeStyle='#fff';c.lineWidth=3;c.setLineDash([22,20]);for(let y=196;y<500;y+=76){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}c.setLineDash([])}c.fillStyle='#173047';c.font='900 19px Arial';c.textAlign='center';c.fillText(type==='swim'?'SWIM ARENA':type==='bike'?'BIKE ARENA':'RUN ARENA',500,44);c.restore()},
crowdPerson(c,x,y,color){c.save();c.translate(x,y);c.fillStyle=color;c.fillRect(-5,-2,10,13);c.fillStyle='#e5ad82';c.beginPath();c.arc(0,-9,6,0,7);c.fill();c.strokeStyle=color;c.lineWidth=3;c.lineCap='round';c.beginPath();c.moveTo(-4,0);c.lineTo(-11,-15);c.moveTo(4,0);c.lineTo(11,-15);c.stroke();c.restore()},
finishZone(c,start,t){let w=400;c.save();c.translate(start,0);c.fillStyle='#bfe8ff';c.fillRect(0,0,w,500);c.fillStyle='#f4d35e';c.fillRect(0,146,w,354);c.fillStyle='rgba(255,255,255,.4)';for(let x=0;x<w;x+=48)for(let y=160;y<500;y+=48)if(((x+y)/48)%2<1)c.fillRect(x,y,48,48);c.fillStyle='#173047';c.font='900 19px Arial';c.textAlign='center';c.fillText('FINISH ZONE',w/2,44);let colors=['#ef3e48','#16aaa9','#f2bd28','#84d42e','#ff8c42','#a15be0'];for(let i=0;i<8;i++){let x=15+i*50;this.crowdPerson(c,x,128-Math.abs(Math.sin(t*7+i*1.3))*9,colors[i%colors.length]);this.crowdPerson(c,x,486-Math.abs(Math.sin(t*7+i*1.7+2))*9,colors[(i+3)%colors.length])}c.restore()},
/* Camera easing uses a flat per-render-call factor rather than being tied to sim dt — purely cosmetic, and decoupling it keeps rendering free to run at whatever rate the browser actually delivers frames. */
draw(t){let c=this.c,w=this.canvas.width,h=this.canvas.height;c.clearRect(0,0,w,h);this.camera+=(this.racers[0].progress*3000-this.camera-280)*.08;this.camera=Math.max(0,Math.min(2400,this.camera));c.save();c.translate(-this.camera,0);this.arena(c,0,'swim',t);this.arena(c,1000,'bike',t);this.arena(c,2000,'run',t);this.finishZone(c,3000,t);this.line(c,0,'START');this.line(c,1000,'SWIM FINISH / BIKE START');this.line(c,2000,'BIKE FINISH / RUN START');this.line(c,3000,'FINISH');this.racers.forEach(r=>{let x=r.progress*3000,y=165+r.lane*76,leg=r.progress<1/3?'swim':r.progress<2/3?'bike':'run';Racers.drawPerson(c,r,x,y,leg,t,1);if(r.flashLeft>0){c.globalAlpha=Math.min(1,r.flashLeft*2);c.fillStyle=r.flash==='SURGE!'?'#177d41':'#b52a35';c.font='900 12px Arial';c.textAlign='center';c.fillText(r.flash,x,y-47)}});c.restore();let fade=c.createLinearGradient(0,0,90,0);fade.addColorStop(0,'#dff5ff');fade.addColorStop(1,'transparent');c.fillStyle=fade;c.fillRect(0,0,90,h)}};
